# Generated by Django 4.0.4 on 2022-04-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0004_neighbourhood_neighbor_alter_neighbourhood_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='neighbor',
        ),
    ]
